### ISSUE TITLE
`NoClassDefFoundError: io/jonasg/bob/TestDefaultsResolver` after upgrading from v0.7.0 to v0.8.0

### ISSUE THREAD

**Issue by donalmurtagh** [jonas-grgt/bob#81]
I started making the changes discussed in [this comment](https://github.com/jonas-grgt/bob/issues/78#issuecomment-4952029085), but after upgrading from v0.7.0 to v0.8.0 (without making any other changes), I now get this exception at runtime (when running my tests that use Bob builders)

```
java.lang.NoClassDefFoundError: io/jonasg/bob/TestDefaultsResolver
```

If you can't reproduce the problem, I can try to make a small repository that demonstrates it?

**Comment by donalmurtagh** [comment]
This looks like another manifestation of the same underlying problem

1. I migrated from `@Buildable.Defaults` to `@Buiildable.TestDefaults` as per [this comment](https://github.com/jonas-grgt/bob/issues/78#issuecomment-4952029085)
2. `Buiildable.TestDefaults` was not available on the test classpath
3. I resolved this by adding a dependency `testCompileOnly "io.jonasg:bob-annotations:0.8.0"`
4. I get `NoClassDefFoundError: io/jonasg/bob/TestDefaultsResolver` when I run the tests
5. I replaced `testCompileOnly "io.jonasg:bob-annotations:0.8.0"` and `compileOnly "io.jonasg:bob-annotations:0.8.0"`with `implementation "io.jonasg:bob-annotations:0.8.0"`
6. I no longer get any runtime or compile-time errors, but the builder defaults are not applied

In summary, no matter how I configure the dependency on `io.jonasg:bob-annotations:0.8.0`, I can't make`Buiildable.TestDefaults` work as advertised.

**Comment by jonas-grgt** [comment]
I've tested it using maven, not a Gradle user. Will look into it and will try to replicate it once I'm back from holiday as no laptop at hand right now.

**Comment by donalmurtagh** [comment]
FYI, a quick way to bootstrap a Gradle project that you can use to reproduce the issue is via https://start.spring.io/

**Comment by jonas-grgt** [comment]
Found the issue. It is in TestDefaultsResolver it does not really use the TestDefaults annotation to load the class. 
Will be fixed next week or if you feel adventures you could give it a shot?

**Comment by jonas-grgt** [comment]
I needed to make some significant changes to fix the issue, like introducing new modules.
The README should contain enough info on how to setup things now, please let me now if it is clear and satisfies your needs?
will release `0.9.0` today
